routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\NovelController;
use App\Http\Controllers\ChapterController;
use App\Http\Controllers\IndexController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class, 'home']);
Route::get('/read/{id}', [IndexController::class, 'read'])->name('read');
Route::get('/novel-category/{slug}', [IndexController::class, 'novel_category'])->name('novel-category');
Route::get('/read-chapter/{slug}', [IndexController::class, 'read_chapter'])->name('read-chapter');
Route::get('/search', [IndexController::class, 'search'])->name('search');


Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('/category', CategoryController::class);

Route::resource('/novel', NovelController::class);

Route::resource('/chapter', ChapterController::class);

app/Models/Chapter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Chapter extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $fillable = [
        'novel_id',
        'describe',
        'status',
        'title',
        'content',
        'slug_chapter',
    ];
    protected $primaryKey = 'id';

    protected $table = 'chapter';

    public function novel() {
        return $this->belongsTo('App\Models\Novel');
    }
}

app/Http/Controllers/ChapterController.php
<?php

namespace App\Http\Controllers;

use App\Models\Chapter;
use App\Models\Novel;
use Illuminate\Http\Request;

class ChapterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $chapters = Chapter::with('novel')->orderBy('id', 'DESC')->get();
        return view('admin.chapter.index')->with(compact('chapters'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $novels = Novel::orderBy('id', 'DESC')->get();

        return view('admin.chapter.create')->with(compact('novels'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate(
            [
                'title' => 'required|unique:chapter|max:255',
                'slug_chapter' => 'required|unique:chapter|max:255',
                'describe' => 'required',
                'status' => 'required',
                'content' => 'required',
                'novel' => 'required',
            ],
            [
                // Sửa lại thông báo validate
                'title.unique' => 'Tên truyện đã tồn tại',
                'slug_chapter.unique' => 'Slug truyện đã tồn tại',
                'title.required' => 'Bạn phải điền tên truyện',
                'slug_chapter.required' => 'Bạn phải điền slug_truyện',
                'describe.required' => 'Bạn phải điền mô tả truyện',
                'content.required' => 'Bạn phải điền nội dung truyện',
            ]
        );

        $chapter = new Chapter();
        $chapter->title = $data['title'];
        $chapter->slug_chapter = $data['slug_chapter'];
        $chapter->describe = $data['describe'];
        $chapter->content = $data['content'];
        $chapter->status = $data['status'];
        $chapter->novel_id = $data['novel'];

        $chapter->save();
        return redirect()->back()->with('status', 'Thêm chương thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $novels = Novel::orderBy('id', 'DESC')->get();
        $chapter = Chapter::find($id);
        return view('admin.chapter.edit')->with(compact('novels', 'chapter'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate(
            [
                'title' => 'required|max:255',
                'slug_chapter' => 'required|max:255',
                'describe' => 'required',
                'status' => 'required',
                'content' => 'required',
                'novel' => 'required',
            ],
            [
                // Sửa lại thông báo validate
                'title.required' => 'Bạn phải điền tên truyện',
                'slug_chapter.required' => 'Bạn phải điền slug_truyện',
                'describe.required' => 'Bạn phải điền mô tả truyện',
                'content.required' => 'Bạn phải điền nội dung truyện',
            ]
        );

        $chapter = Chapter::find($id);
        $chapter->title = $data['title'];
        $chapter->slug_chapter = $data['slug_chapter'];
        $chapter->describe = $data['describe'];
        $chapter->content = $data['content'];
        $chapter->status = $data['status'];
        $chapter->novel_id = $data['novel'];

        $chapter->save();
        return redirect()->back()->with('status', 'Cập nhật chương thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Chapter::find($id)->delete();
        return redirect()->back()->with('status', 'Xoá chương thành công');
    }
}

resources/views/admin/chapter/create.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.nav')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Thêm chương truyện</div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST" action="{{ route('chapter.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="mb-3">
                                <label class="form-label">Tên chương</label>
                                <input type="text" value="{{ old('title') }}" class="form-control" name="title"
                                    onkeyup="ChangeToSlug()" placeholder="Tên chương" id="slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Slug chương</label>
                                <input type="text" value="{{ old('slug_chapter') }}" class="form-control" name="slug_chapter"
                                    readonly placeholder="Slug chương" id="convert_slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Mô tả chương</label>
                                <input name="describe" value="{{ old('describe') }}" class="form-control" rows="5" style="resize: none;"></input>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Nội dung chương</label>
                                <textarea id="content_chapter" name="content" value="{{ old('content') }}" class="form-control" rows="5" style="resize: none;"></textarea>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Thuộc truyện</label>
                                <select name="novel" class="form-select" aria-label="Default select example">
                                    @foreach ($novels as $key => $novel)
                                        <option value="{{ $novel->id }}">{{ $novel->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Trạng thái</label>
                                <select name="status" class="form-select" aria-label="Default select example">
                                    <option value="0">Kích hoạt</option>
                                    <option value="1">Không kích hoạt</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Thêm chương</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/chapter/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.nav')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Cập nhật chương truyện</div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST" action="{{ route('chapter.update', $chapter->id) }}" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="mb-3">
                                <label class="form-label">Tên chương</label>
                                <input type="text" value="{{ $chapter->title }}" class="form-control" name="title"
                                       onkeyup="ChangeToSlug()" placeholder="Tên chương" id="slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Slug chương</label>
                                <input type="text" value="{{ $chapter->slug_chapter }}" class="form-control" name="slug_chapter"
                                       readonly placeholder="Slug chương" id="convert_slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Mô tả chương</label>
                                <input name="describe" value="{{ $chapter->describe }}" class="form-control" rows="5" style="resize: none;"></input>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Nội dung chương</label>
                                <textarea id="content_chapter" name="content" value="" class="form-control" rows="5" style="resize: none;">{{ $chapter->content }}</textarea>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Thuộc truyện</label>
                                <select name="novel" class="form-select" aria-label="Default select example">
                                    @foreach ($novels as $key => $novel)
                                        <option {{ $chapter->novel_id == $novel->id ? "selected" : "" }} value="{{ $novel->id }}">{{ $novel->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Trạng thái</label>
                                <select name="status" class="form-select" aria-label="Default select example">
                                    @if ($chapter->status == 0)
                                        <option selected value="0">Kích hoạt</option>
                                        <option value="1">Không kích hoạt</option>
                                    @else
                                        <option value="0">Kích hoạt</option>
                                        <option selected value="1">Không kích hoạt</option>
                                    @endif
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Thêm chương</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/chapter/index.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.nav')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Danh sách truyện</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <a class="btn btn-success mb-3" href="{{ route('chapter.create') }}" role="button">Thêm chương</a>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Tên chương</th>
                                    <th scope="col">Slug chương</th>
                                    <th scope="col">Mô tả</th>
                                    <th scope="col">Truyện</th>
                                    <th scope="col">Trạng thái</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($chapters as $key => $chapter)
                                    <tr>
                                        <th scope="row">{{ $key }}</th>
                                        <td>{{ $chapter->title }}</td>
                                        <td>{{ $chapter->slug_chapter }}</td>
                                        <td>{{ $chapter->describe }}</td>
                                        <td>{{ $chapter->novel->name }}</td>
                                        <td>
                                            @if ($chapter->status == 0)
                                                <span class="text text-success">Kích hoạt</span>
                                            @else
                                                <span class="text text-danger">Không kích hoạt</span>
                                            @endif
                                        </td>
                                        <td>

                                            <form class="d-flex" action="{{ route('chapter.destroy', $chapter->id) }}"
                                                  method="POST">
                                                <div style="margin-right: 20px;">
                                                    <a class="btn btn-primary"
                                                       href="{{ route('chapter.edit', $chapter->id) }}"
                                                       role="button">Sửa</a>
                                                </div>
                                                @method('DELETE')
                                                @csrf
                                                <button onclick="return confirm('Bạn muốn xóa chương này không ?');"
                                                        class="btn btn-danger">Xoá</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection