routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\NovelController;
use App\Http\Controllers\ChapterController;
use App\Http\Controllers\IndexController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class, 'home']);
Route::get('/read/{id}', [IndexController::class, 'read'])->name('read');
Route::get('/novel-category/{slug}', [IndexController::class, 'novel_category'])->name('novel-category');
Route::get('/read-chapter/{slug}', [IndexController::class, 'read_chapter'])->name('read-chapter');
Route::get('/search', [IndexController::class, 'search'])->name('search');


Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::resource('/category', CategoryController::class);

Route::resource('/novel', NovelController::class);

Route::resource('/chapter', ChapterController::class);

app/Models/Novel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Novel extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $fillable = [
        'name',
        'describe',
        'status',
        'slug_novel',
        'image',
        'category_id',
    ];
    protected $primaryKey = 'id';

    protected $table = 'novel';

    public function category() {
        return $this->belongsTo('App\Models\Category', 'category_id', 'id');
    }

    public function chapter() {
        return $this->hasMany('App\Models\Chapter', 'novel_id', 'id');
    }
}

app/Http/Controllers/NovelController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Novel;
use Illuminate\Http\Request;

class NovelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $novels = Novel::with('category')->orderBy('id', 'DESC')->get();
        return view('admin.novel.index')->with(compact('novels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('id', 'DESC')->get();
        return view('admin.novel.create')->with(compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate(
            [
                'name' => 'required|unique:novel|max:255',
                'author' => 'required|unique:novel|max:255',
                'slug_novel' => 'required|unique:novel|max:255',
                'describe' => 'required',
                'status' => 'required',
                'image' => 'required|image|mimes:jpg,png,jepg,svg|max:2048|dimensions:min_width=100,min_height=100,
                max_width=1920,max_height=1080',
                'category' => 'required',
            ],
            [
                // Sửa lại thông báo validate
                'name.unique' => 'Tên truyện đã tồn tại',
                'slug_novel.unique' => 'Slug truyện đã tồn tại',
                'name.required' => 'Bạn phải điền tên truyện',
                'author.required' => 'Bạn phải điền tên tác giả',
                'slug_novel.required' => 'Bạn phải điền slug_truyện',
                'describe.required' => 'Bạn phải điền mô tả truyện',
                'image.required' => 'Phải thêm hình ảnh',
            ]
        );

        $novel = new Novel();
        $novel->name = $data['name'];
        $novel->author = $data['author'];
        $novel->slug_novel = $data['slug_novel'];
        $novel->describe = $data['describe'];
        $novel->status = $data['status'];
        $novel->category_id = $data['category'];

        //Thêm ảnh vào folder
        $get_image = $request->image;
        $path = 'public/uploads/novel/';
        $get_name_image = $get_image->getClientOriginalName();
        $name_image = current(explode('.', $get_name_image));
        $new_image = $name_image.rand(0,99) . '.' . $get_image->getClientOriginalExtension();
        $get_image->move($path, $new_image);
        $novel->image = $new_image;

        $novel->save();
        return redirect()->back()->with('status', 'Thêm truyện thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $novel = Novel::find($id);
        $categories = Category::orderBy('id', 'DESC')->get();
        return view('admin.novel.edit')->with(compact('novel', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate(
            [
                'name' => 'required|max:255',
                'author' => 'required|max:255',
                'slug_novel' => 'required|max:255',
                'describe' => 'required',
                'status' => 'required',
                'category' => 'required',
            ],
            [
                // Sửa lại thông báo validate

                'name.required' => 'Bạn phải điền tên truyện',
                'author.required' => 'Bạn phải điền tên tác giả',
                'slug_novel.required' => 'Bạn phải điền slug_truyện',
                'describe.required' => 'Bạn phải điền mô tả truyện',

            ]
        );

        $novel = Novel::find($id);
        $novel->name = $data['name'];
        $novel->author = $data['author'];
        $novel->slug_novel = $data['slug_novel'];
        $novel->describe = $data['describe'];
        $novel->status = $data['status'];
        $novel->category_id = $data['category'];

        //Thêm ảnh
        $get_image = $request->image;
        if ($get_image) {
            $path = 'public/uploads/novel/' . $novel->image;
            if (file_exists($path)) {
                unlink($path);
            }
            $path = 'public/uploads/novel/';
            $get_name_image = $get_image->getClientOriginalName();
            $name_image = current(explode('.', $get_name_image));
            $new_image = $name_image.rand(0,99) . '.' . $get_image->getClientOriginalExtension();
            $get_image->move($path, $new_image);
            $novel->image = $new_image;
        }
        $novel->save();
        return redirect()->back()->with('status', 'Cập nhật truyện thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $novel = Novel::find($id);
        $path = 'public/uploads/novel/' . $novel->image;
        if (file_exists($path)) {
            unlink($path);
        }
        Novel::find($id)->delete();
        return redirect()->back()->with('status', 'Xóa truyện thành công');
    }
}

resources/views/admin/novel/create.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.nav')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Thêm truyện</div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST" action="{{ route('novel.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="mb-3">
                                <label class="form-label">Tên truyện</label>
                                <input type="text" value="{{ old('name') }}" class="form-control" name="name"
                                    onkeyup="ChangeToSlug()" placeholder="Tên truyện" id="slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Tác giả</label>
                                <input type="text" value="{{ old('author') }}" class="form-control" name="author"
                                       onkeyup="ChangeToSlug()" placeholder="Tên tác giả" id="slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Slug truyện</label>
                                <input type="text" value="{{ old('slug_novel') }}" class="form-control" name="slug_novel"
                                    readonly placeholder="Slug truyện" id="convert_slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Mô tả truyện</label>
                                <textarea id="describe_novel" name="describe" class="form-control" rows="5" style="resize: none;"></textarea>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Danh mục truyện</label>
                                <select name="category" class="form-select" aria-label="Default select example">
                                    @foreach ($categories as $key => $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Hình ảnh truyện</label>
                                <input type="file" class="form-control-file" name="image">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Trạng thái</label>
                                <select name="status" class="form-select" aria-label="Default select example">
                                    <option value="0">Kích hoạt</option>
                                    <option value="1">Không kích hoạt</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Thêm truyện</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/novel/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.nav')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Cập nhật truyện</div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST" action="{{ route('novel.update', $novel->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="mb-3">
                                <label class="form-label">Tên truyện</label>
                                <input type="text" value="{{ $novel->name }}" class="form-control" name="name"
                                    onkeyup="ChangeToSlug()" placeholder="Tên truyện" id="slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Tác giả</label>
                                <input type="text" value="{{ $novel->author }}" class="form-control" name="author"
                                       onkeyup="ChangeToSlug()" placeholder="Tên tác giả" id="slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Slug truyện</label>
                                <input type="text" value="{{ $novel->slug_novel }}" class="form-control" name="slug_novel"
                                    readonly placeholder="Slug truyện" id="convert_slug">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Mô tả truyện</label>
                                <textarea id="describe_novel" name="describe" class="form-control" rows="5" style="resize: none;">{{ $novel->describe }}</textarea>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Danh mục truyện</label>
                                <select name="category" class="form-select" aria-label="Default select example">
                                    @foreach ($categories as $key => $category)
                                        <option {{ $category->id == $novel->category_id ? 'selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Hình ảnh truyện</label>
                                <input type="file" class="form-control-file" name="image">
                                <img src="{{ asset('public/uploads/novel/'.$novel->image) }}"
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Trạng thái</label>
                                <select name="status" class="form-select" aria-label="Default select example">
                                    @if ($novel->status == 0)
                                        <option selected value="0">Kích hoạt</option>
                                        <option value="1">Không kích hoạt</option>
                                    @else
                                        <option value="0">Kích hoạt</option>
                                        <option selected value="1">Không kích hoạt</option>
                                    @endif

                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Cập nhật truyện</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/novel/index.blade.php
@extends('layouts.app')

@section('content')
    @include('layouts.nav')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Danh sách truyện</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <a class="btn btn-success mb-3" href="{{ route('novel.create') }}" role="button">Thêm truyện</a>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Tên truyện</th>
                                    <th scope="col">Tác giả</th>
                                    <th scope="col">Hình ảnh</th>
                                    <th scope="col">Slug truyện</th>

                                    <th scope="col">Danh mục</th>
                                    <th scope="col">Trạng thái</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($novels as $key => $novel)
                                    <tr>
                                        <th scope="row">{{ $key }}</th>
                                        <td>{{ $novel->name }}</td>
                                        <td>{{ $novel->author }}</td>
                                        <td><img src="{{ asset('public/uploads/novel/'.$novel->image) }}" height="200" width="200" alt=""></td>
                                        <td>{{ $novel->slug_novel }}</td>

                                        <td>{{ $novel->category->name }}</td>
                                        <td>
                                            @if ($novel->status == 0)
                                                <span class="text text-success">Kích hoạt</span>
                                            @else
                                                <span class="text text-danger">Không kích hoạt</span>
                                            @endif
                                        </td>
                                        <td>

                                            <form class="d-flex" action="{{ route('novel.destroy', $novel->id) }}"
                                                method="POST">
                                                <div style="margin-right: 20px;">
                                                    <a class="btn btn-primary"
                                                        href="{{ route('novel.edit', $novel->id) }}"
                                                        role="button">Sửa</a>
                                                </div>
                                                @method('DELETE')
                                                @csrf
                                                <button onclick="return confirm('Bạn muốn xóa truyện này không ?');"
                                                    class="btn btn-danger">Xoá</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection